name = "geosocio"
type = "webpack"
account_id = "2659099e440328a773821e7db5363a84"
workers_dev = false
route = "geosoc.io/*"
zone_id = "840ab5dd05a8ec9ac55993bbde29319f"

[site]
bucket = "./public"
entry-point = ""
